name: Release new version

on:
  pull_request:
    branches:
      - main
    types: closed

jobs:
  release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.pull_request.head.ref }}
          release_name: ${{ github.event.pull_request.head.ref }}
          draft: false
          prerelease: false
